modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="epoch_of_the_elementals"
version="1.0.0"
displayName="Epoch of the Elementals"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="iamsc, MCreator"

[[dependencies.epoch_of_the_elementals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




